<?php

namespace App\Controller;

use App\Controller\AppController;

class TheameController extends AppController{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout("theamelayout");
    }

    public function index(){
        $this->set('title', 'Convert in cakePHP');
    }
}
